### This is the name the plugin will use when logging and will be the start of the permission ###
### Example Name: 'SaberCannon' means that permissions will be sabercannon.node ###
Name: 'SaberCannon'
### If a player carries this item they cannot be automatically targeted NOT IN USE ###
GhostItem:
  Material: 'NETHER_STAR'
  Name: 'Infrared Countermeasure'
  Lore:
    - '&bWhile having this in your inventory you'
    - '&bcannot be seen by the %plugin%'
  Glow: true
WorldGuard:
  ### Add regions players cant die in so that they will not show up in autotarget ###
  BlacklistedRegions:
    - 'Spawn'
  ForcedRegions:
    Enabled: false
    Regions:
      - 'Orbital'
Cost:
  Manual:
    StartingPrice: 100000
    PricePerExtraTNT: 50000
  Automatic:
    StartingPrice: 120000
    PricePerExtraTNT: 50000
Title:
  ### A title is large text that appears on your screen Ex. when walking into a claim of a different faction ###
  ### It is suggested to use SaberFactions or the title will get overridden when the player respawns ###
  Enabled: true
  Message: '&4Obliterated'
### Autorespawns players that have died to the cannon ###
AutoRespawn: true
### These settings change how the player gets to view their manual strikes ###
PlayerView:
  ## PlayerView will be disabled if you are using Essentials vanish as it would reveal vanished players ##
  BlocksAboveExplosion: 50
  NightVision: true
  ## Time in seconds this player will view the explosion ###
  Time: 5
  ## If a player leaves during the view they are automatically added to a list and saved so when they rejoin the plugin can take action. ##
  ## If no action is taken the player might just be able to fly around in free mode constantly and teleport large distances ##
  ## Strategies: Spawn, FactionHome ##
  ## Spawn: Sets the players gamemode back to survival and teleports them to the world spawn. ##
  ## FactionHome: If a player is in a faction and is allowed to teleport home they will have their gamemode set to survival and be summoned there. Fallback: Spawn ##
  ExploitPrevention:
    Strategy: FactionHome
Limits:
  ## TNTPower changes how many blocks surrounding the explosions are effected ##
  TNTPower: 4
  MaximumTNTPerStrike: 64
  ## ForcedRegions are good if you would like player to have to go to a certain spot to use the cannon! ##
FactionsHook:
  ### Only disable your factions plugin is not supported as the plugin will automatically determine if the plugin is enabled ###
  ### Supported plugins: SaberFactions, SavageFactions, FactionsUUID ###
  Enabled: true
  ### Determine which system factions the cannon can hit ###
  SafeZone: false
  WarZone: true
  Wild: true
### This multi layer GUI handles most of the input for players ###
GUI:
  FillItem:
    Material: 'BLACK_STAINED_GLASS_PANE'
    Name: ' '
    Lore:
      - ''
  BackItem:
    Material: 'RED_STAINED_GLASS_PANE'
    Name: '&cBack'
  ContinueItem:
    Material: 'GREEN_STAINED_GLASS_PANE'
    Name: '&2Continue'
## Layer One is where players can choose between auto and manual targeting ##
  LayerOne:
    ### MineCraft versions <1.13 have access to Titles ### # not implemented yet #
    Title: '&bChoose Targeting'
    Size: 27
    ManualItem:
      Material: 'EYE_OF_ENDER'
      Name: '&bManual Targeting'
      Lore:
        - '&bStrike based on coordinates.'
      Slot: 12
    AutoItem:
      Material: 'BEACON'
      Name: '&bAutomatic Targeting'
      Lore:
        - '&bStrike using precise calculation to target players.'
      Slot: 14
### Layer Two is where the player will choose their payload ###
  LayerTwo:
    Title: '&bSelect Payload'
    Size: 9
    IncreaseItem:
      Material: 'GREEN_STAINED_GLASS_PANE'
      Name: '&2Increase Payload'
      Lore:
        - '&bIncrease the size of your strike!'
        - '&bManual &2$50,000&b per explosive'
        - '&bAutomatic &2$75,000&b per explosive'
      Slot: 3
    PayloadItem:
      Material: 'TNT'
      Name: '&cPayload'
      Lore:
        - '&bYour current payload.'
      Slot: 4
    DecreaseItem:
      Material: 'RED_STAINED_GLASS_PANE'
      Name: '&cDecrease Payload'
      Lore:
        - '&bDecrease the size of your strike.'
      Slot: 5
## Navigation items do not require to be re-setup ##
    BackItem:
      Slot: 0
    ContinueItem:
      Slot: 8
### Layer three is the player head GUI only show to automatically targeting players ###
  LayerThree:
    Title: '&bSelect Target'
    Size: 54
## Layer three has no nav buttons so they have to pick their target ##
  ConfirmationMenu:
    Title: '&bConfirmation'
    Size: 9
    ConfirmItem:
      Material: 'Nether_Star'
      Name: '&2Confirm your strike'
      Lore:
        - ''
      Slot: 4
    CancelItem:
      Material: 'RED_STAINED_GLASS_PANE'
      Name: '&cCancel your strike'
      Lore:
        - ''
      Slot: 8
Messages:
  NothingToConfirm: '&bYou do not have anything to confirm.'
  ClearedStrikes: '&bCleared your StrikeOrder data.'
  MustBePlayer: 'You must be a player to run this command!'
  ### You may use %cost% anywhere in the ConfirmMessage ###
  ConfirmMessage:
    - '&b&l&oConfirmation'
    - '&bPlease type &d/strike confirm&b again to confirm'
    - '&bStrikeOrder cost: &2$%cost%'
  CannotRunMultipleStrikes:
    - '&bYou cannot create multiple strikes at once.'
    - '&bIf you are trying to confirm a strike use &d/strike confirm'
    - '&bif you would like to make a new strike use &d/strike clear'
  InstructionsForManual:
    - '&bYou have selected manual strike!'
    - '&bPlease type the x and z in chat separated by a space.'
    - '&7Note: Other players will not see this message.'
  InstructionsNotFollowedHelp:
    - '&bPlease only type the X and Z coordinates separated by one space.'
    - '&bExample: ''56 32'' '
  ManualCoordsSet:
    - '&b&l&o Success!'
    - '&bYour strike coordinates are set to x&d%x%&b,z&d%z%'
    - '&bWhen you are ready type ''&d/strike confirm&b'' to continue'
  AutomaticTargetSet:
    - '&b&l&o Success!'
    - '&bYour strike target is set to ''&d%TargetDisplayName%&b'' AKA ''&d%Target%&b'''
    - '&bWhen you are ready type ''&d/strike confirm&b'' to continue'
  NotEnoughMoney: '&cSorry, you have insufficient funds.'
  AutomaticStrikeReady:
    - '&b&l&oSuccess!'
    - '&bYour strike is ready please confirm it using &d/strike confirm'
  ### This death message is provided when a player is killed by automatic targeting. Available placeholders: %victim% %striker% %plugin% ###
  DeathMessage: '&c%victim% has been obliterated by %striker%'
  TargetNotFound:
    - '&bWe lost track of that target please try again later.'
    - '&7Note: Players can get out of sight in an instant strike fast!'
  NotInWGRegion:
    - '&cYou cannot access the cannon from this location!'
    - '&bYou can access the cannon at the Orbital room at spawn.'
  ForbiddenTargetRegion:
    - '&cYou cannot strike this location!'







